import { useState } from 'react'

export default function RoomCard({ listing }) {
  const [showOriginal, setShowOriginal] = useState(false)

  // Fallback for listings missing data
  if (!listing) return null;

  return (
    <div className="room-card border border-border/50 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300">

      {/* Image with before/after toggle */}
      <div className="card-image-wrap relative h-48 w-full overflow-hidden bg-muted">
        <img
          src={showOriginal
            ? listing.original_url || `https://source.unsplash.com/random/800x600/?${listing.room_type || 'interior'}`
            : listing.hero_image_url || `https://source.unsplash.com/random/800x600/?${listing.room_type || 'interior'},enhanced`}
          alt={listing.location || "Property Image"}
          className="card-image w-full h-full object-cover"
        />

        {/* Before/After toggle */}
        <button
          className="absolute bottom-2 right-2 px-2 py-1 bg-black/60 text-white text-xs rounded backdrop-blur-sm hover:bg-black/80 transition-colors"
          onClick={() => setShowOriginal(!showOriginal)}
        >
          {showOriginal ? 'Show Enhanced' : 'Show Original'}
        </button>

        {/* Quality grade badge */}
        {listing.quality_grade && (
            <span className={`absolute top-2 left-2 px-2 py-1 rounded text-xs font-bold shadow-sm ${
                listing.quality_grade === 'A' ? 'bg-green-500 text-white' : 
                listing.quality_grade === 'B' ? 'bg-blue-500 text-white' : 
                listing.quality_grade === 'C' ? 'bg-yellow-500 text-white' : 'bg-red-500 text-white'
            }`}>
              Grade {listing.quality_grade}
            </span>
        )}

        {/* Match score */}
        {listing.match_score > 0 && (
            <span className="absolute top-2 right-2 px-2 py-1 bg-primary text-primary-foreground font-bold rounded-full text-xs shadow-sm">
            {listing.match_score}% match
            </span>
        )}
      </div>

      {/* Room tags — auto-generated by classifier */}
      <div className="p-4 flex flex-col gap-3">
          <div className="flex flex-wrap gap-2">
            {listing.room_tags?.map(tag => (
              <span key={tag} className="px-2 py-1 bg-secondary/10 text-secondary text-[10px] uppercase font-bold tracking-wider rounded-sm">{tag}</span>
            ))}
            {listing.vastu_compliant && (
              <span className="px-2 py-1 bg-amber-500/10 text-amber-600 text-[10px] uppercase font-bold tracking-wider rounded-sm">Vastu</span>
            )}
          </div>

          {/* Property info */}
          <div className="flex flex-col gap-1">
            <div className="text-xl font-bold text-foreground">{listing.price_formatted || `₹${(listing.price || 0).toLocaleString()}`}</div>
            <div className="text-sm font-medium text-secondary/80">
              {listing.bhk ? `${listing.bhk} BHK · ` : ''}{listing.property_type || 'Property'} · {listing.city || 'Location'}
            </div>
            <div className="text-xs text-secondary/60 line-clamp-1">{listing.location}</div>
          </div>

          {/* Claude match explanation */}
          {listing.match_explanation && (
            <p className="text-xs text-secondary/70 italic border-t border-border/50 pt-2 mt-1">
              {listing.match_explanation}
            </p>
          )}
      </div>
    </div>
  )
}
